{
 "title": "Adaptive Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app_method) (nginx_http_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(nginx_http_requests{app_status=~\"2..\"})",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(nginx_http_requests{app_status=~\"4..\"})",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(nginx_http_requests{app_status=~\"5..\"})",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latencies by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(app_prefix) (nginx_adpt_latencies)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IFR by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(app_prefix) (nginx_http_ifr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_prometheus_errors_total", "legendFormat": "prometheus" },
    { "expr": "nginx_adpt_reject", "legendFormat": "rejection" }
   ]
  }
 ]
}